import type { Metadata } from "next";
import { Atma, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers/index";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const atma = Atma({
	weight: ["400", "500"],
	variable: "--font-heading",
});

const inter = Inter({
	weight: ["400", "500"],
	variable: "--font-body",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${atma.variable} ${inter.variable}`}>
			<body>
				<main>
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	);
}
